url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "NIPH Infectious Disease Modelling" # the name of your site, e.g. ACME Corp.
description: "Norwegian Institute of Public Health (Folkehelseinstituttet)"
