#theme: jekyll-theme-minimal
remote_theme: academic-jekyll-theme
lsi: false
safe: true
source: "/"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge