menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Birgitte Freiesleben de Blasio', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'birgitte'}
- {name: 'Gunnar Øyvind Isaksson Rø', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'gunnar'}
- {name: 'Sasikiran Kandula', title: 'Senior Engineer', department: 'Methods Development and Analysis', institution: 'Folkehelseinstituttet', institution_address: 'Lovisenberggata 8, 0456 Oslo', email: '', office: '', image: 'assets/img/graduate-student.jpg', url: 'sasi'}

courses:
- {name: '', url: ''}


social:
- {icon: 'github', link: 'https://github.com/folkehelseinstituttet'}
- {icon: 'twitter', link: 'https://twitter.com/Folkehelseinst'}
- {icon: 'instagram', link: 'https://www.instagram.com/folkehelseinstituttet/'}
- {icon: 'linkedin', link: 'https://no.linkedin.com/company/norwegian-institute-of-public-health'}

contacts:
- {name: 'Prof. Birgitte Freiesleben de Blasio', title: 'Department Director, Professor II', department: 'Methods Development and Analysis', institution: 'Folkehelseinstituttet', institution_address: 'Lovisenberggata 8, 0456 Oslo', email: '', office: '', image: 'assets/img/contact.jpg'}
